$folders = @(
"config",
"controllers",
"models",
"routes",
"services",
"middlewares",
"utils",
"database",
"uploads",
"uploads/products",
"public",
"public/css",
"public/js",
"public/img",
"public/img/icons",
"views"
)

foreach($folder in $folders){
    New-Item -ItemType Directory -Force -Path $folder | Out-Null
}

$files = @(
".env",
".gitignore",
"README.md",
"server.js",

"config/db.js",
"config/jwt.js",
"config/multer.js",

"controllers/authController.js",
"controllers/bancoController.js",
"controllers/boletaController.js",
"controllers/cargoController.js",
"controllers/categoriaController.js",
"controllers/clienteController.js",
"controllers/contratoController.js",
"controllers/dashboardController.js",
"controllers/departamentoController.js",
"controllers/detallePedidoController.js",
"controllers/deudaController.js",
"controllers/distritoController.js",
"controllers/egresoController.js",
"controllers/empleadoController.js",
"controllers/empresaController.js",
"controllers/facturaController.js",
"controllers/ingresoController.js",
"controllers/mesaController.js",
"controllers/metodoPagoController.js",
"controllers/pedidoController.js",
"controllers/personaController.js",
"controllers/productoController.js",
"controllers/provinciaController.js",
"controllers/reservaController.js",
"controllers/tipoUsuarioController.js",
"controllers/usuarioController.js",
"controllers/ventaController.js",
"controllers/zonaController.js",

"models/bancoModel.js",
"models/boletaModel.js",
"models/cargoModel.js",
"models/categoriaModel.js",
"models/clienteModel.js",
"models/contratoModel.js",
"models/dashboardModel.js",
"models/departamentoModel.js",
"models/detallePedidoModel.js",
"models/deudaModel.js",
"models/distritoModel.js",
"models/egresoModel.js",
"models/empleadoModel.js",
"models/empresaModel.js",
"models/facturaModel.js",
"models/ingresoModel.js",
"models/mesaModel.js",
"models/metodoPagoModel.js",
"models/pedidoModel.js",
"models/personaModel.js",
"models/productoModel.js",
"models/provinciaModel.js",
"models/reservaModel.js",
"models/tipoUsuarioModel.js",
"models/usuarioModel.js",
"models/ventaModel.js",
"models/zonaModel.js",

"routes/authRoutes.js",
"routes/bancoRoutes.js",
"routes/boletaRoutes.js",
"routes/cargoRoutes.js",
"routes/categoriaRoutes.js",
"routes/clienteRoutes.js",
"routes/contratoRoutes.js",
"routes/dashboardRoutes.js",
"routes/departamentoRoutes.js",
"routes/detallePedidoRoutes.js",
"routes/deudaRoutes.js",
"routes/distritoRoutes.js",
"routes/egresoRoutes.js",
"routes/empleadoRoutes.js",
"routes/empresaRoutes.js",
"routes/facturaRoutes.js",
"routes/ingresoRoutes.js",
"routes/mesaRoutes.js",
"routes/metodoPagoRoutes.js",
"routes/pedidoRoutes.js",
"routes/personaRoutes.js",
"routes/productoRoutes.js",
"routes/provinciaRoutes.js",
"routes/reservaRoutes.js",
"routes/tipoUsuarioRoutes.js",
"routes/usuarioRoutes.js",
"routes/ventaRoutes.js",
"routes/zonaRoutes.js",

"services/authService.js",
"services/bancoService.js",
"services/boletaService.js",
"services/cargoService.js",
"services/categoriaService.js",
"services/clienteService.js",
"services/contratoService.js",
"services/dashboardService.js",
"services/detallePedidoService.js",
"services/deudaService.js",
"services/empleadoService.js",
"services/empresaService.js",
"services/facturaService.js",
"services/ingresoService.js",
"services/mesaService.js",
"services/metodoPagoService.js",
"services/pedidoService.js",
"services/personaService.js",
"services/productoService.js",
"services/reservaService.js",
"services/usuarioService.js",
"services/ventaService.js",
"services/zonaService.js",

"middlewares/authMiddleware.js",
"middlewares/roleMiddleware.js",
"middlewares/uploadMiddleware.js",
"middlewares/validatorMiddleware.js",
"middlewares/errorHandler.js",
"middlewares/notFound.js",

"utils/bcrypt.js",
"utils/jwt.js",
"utils/validators.js",
"utils/response.js",
"utils/pdfGenerator.js",
"utils/excelGenerator.js",
"utils/formatter.js",
"utils/logger.js",
"utils/helpers.js",

"database/db.sql",
"database/seed.sql",
"database/procedures.sql",

"views/index.html",
"views/dashboard.html",
"views/clientes.html",
"views/productos.html",
"views/categorias.html",
"views/empleados.html",
"views/usuarios.html",
"views/reservas.html",
"views/pedidos.html",
"views/ventas.html",
"views/boletas.html",
"views/facturas.html",
"views/ingresos.html",
"views/egresos.html",
"views/mesas.html",
"views/zonas.html",
"views/reportes.html",
"views/perfil.html",
"views/configuracion.html",
"views/404.html",
"views/500.html"
)

foreach($file in $files){
    New-Item -ItemType File -Force -Path $file | Out-Null
}

Write-Host "Estructura creada correctamente."
